name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        rsync -avz --delete \
          --exclude '.git' \
          --exclude '.github' \
          --exclude 'README.md' \
          --exclude '.gitignore' \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app/

    - name: Deploy on EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/app
          
          # Stop existing containers
          docker-compose down --remove-orphans || true
          
          # Remove old images to free space
          docker system prune -f
          
          # Build and start new containers
          docker-compose up --build -d
          
          # Show running containers
          docker-compose ps
          
          # Show logs for verification
          docker-compose logs --tail=20
        EOF

    - name: Health Check
      run: |
        sleep 60  # Wait for services to start
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Test health endpoints
          curl -f http://localhost:8080/health || exit 1
          curl -f http://localhost:8080/service1/ping || exit 1
          curl -f http://localhost:8080/service2/ping || exit 1
          echo "All health checks passed!"
        EOF
